AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "me-test"
Description: "Stack used to start and stop bot and pipeline."

Resources:
  BotS3Bucket:
    Type: "AWS::S3::Bucket"
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      BucketName: "renzen-bot-s3-bucket"
  Init:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cloudformation-files-renzen.s3.us-west-1.amazonaws.com/cloudformation/stacks/bot_stack/nested/init_stack.yml"
  BotCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: BotCodePipeline
      RoleArn: !ImportValue BotPipelineRole
      ArtifactStore:
        Location: !Ref BotS3Bucket
        Type: "S3"
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              Configuration:
                BranchName: !ImportValue GitHubBranchName
                ConnectionArn: !ImportValue BotGithubConnection
                FullRepositoryId: !ImportValue GitHubRepoName
                OutputArtifactFormat: "CODE_ZIP"
              OutputArtifacts:
                - Name: SourceArtifact
              Region: !Ref AWS::Region
              Namespace: "SourceVariables"
              RunOrder: 1
        - Name: "Build"
          Actions:
            - Name: "Build"
              ActionTypeId:
                Category: "Build"
                Owner: "AWS"
                Provider: "CodeBuild"
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: "SourceArtifact"
              OutputArtifacts:
                - Name: "secondary_artifact_name_1"
                - Name: "secondary_artifact_name_2"
              Region: !Ref AWS::Region
              Namespace: "BuildVariables"
              RunOrder: 1
        - Name: "DeployBot"
          Actions:
            - Name: "DeployMyBot"
              ActionTypeId:
                Category: "Deploy"
                Owner: "AWS"
                Provider: "ECS"
                Version: "1"
              Configuration:
                ClusterName: bot-cluster #!Ref ECSCluster
                ServiceName: bot-service #!GetAtt ECSService.Name
              InputArtifacts:
                - Name: "secondary_artifact_name_1"
              Region: !Ref AWS::Region
              Namespace: "DeployVariables"
              RunOrder: 1
            - Name: "DeployMySite"
              ActionTypeId:
                Category: "Deploy"
                Owner: "AWS"
                Provider: "ECS"
                Version: "1"
              Configuration:
                ClusterName: bot-cluster #!Ref ECSCluster
                ServiceName: site-service #!GetAtt ECSService.Name
              InputArtifacts:
                - Name: "secondary_artifact_name_2"
              Region: !Ref AWS::Region
              Namespace: "DeployVariablesSite"
              RunOrder: 1

  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: BotCodeBuildProject-2 # !Sub "${CodeBuildProject3}-3"
      Source:
        InsecureSsl: false
        Type: "CODEPIPELINE"
        BuildSpec: "buildspecs/bot_buildspec.yml"
      Artifacts:
        EncryptionDisabled: false
        Name: BotCodeBuildProject-2 # !Sub "${CodeBuildProject3}-3"
        Packaging: "NONE"
        Type: "CODEPIPELINE"
      Cache:
        Type: "NO_CACHE"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:4.0"
        ImagePullCredentialsType: "CODEBUILD"
        PrivilegedMode: true
        Type: "LINUX_CONTAINER"
      ServiceRole: !ImportValue BotCodeBuildRole
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
        S3Logs:
          Status: "DISABLED"
          EncryptionDisabled: false
      Visibility: "PRIVATE"
# Outputs:
#     GatewayToInternet:
#       Value: !ImportValue Init.GatewayToInternet
#       Export:
#         Name: GatewayToInternet

#     myInternetGateway:
#       Value: !ImportValue myInternetGateway
#       Export:
#         Name: myInternetGateway

#     InstanceSecurityGroup:
#       Value: !ImportValue myStackWithParams.InstanceSecurityGroup
#       Export:
#         Name: InstanceSecurityGroup

#     LoadBalancerSecurityGroup:
#       Value: !ImportValue myStackWithParams.LoadBalancerSecurityGroup
#       Export:
#         Name: LoadBalancerSecurityGroup

#     BotS3Bucket:
#       Value: !ImportValue BotS3Bucket
#       Export:
#         Name: BotS3Bucket

#     myVPC:
#       Value: !ImportValue myVPC
#       Export:
#         Name: myVPC

#     mySubnet1:
#       Value: !ImportValue mySubnet1
#       Export:
#         Name: mySubnet1

#     mySubnet2:
#       Value: !ImportValue myStackWithParams.mySubnet2
#       Export:
#         Name: mySubnet2

#     ECRRepository:
#       Value: !ImportValue ECRRepository
#       Export:
#         Name: ECRRepository

    # QueueName:
    #   Description: The name of the queue
    #   Value: !GetAtt
    #     - MyQueue
    #     - QueueName
    # QueueURL:
    #   Description: The URL of the queue
    #   Value: !ImportValue Init.MyQueue
    # QueueARN:
    #   Description: The ARN of the queue
    #   Value: !GetAtt
    #     - MyQueue
    #     - Arn
