repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    # -   id: check-yaml
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: ["--config-file=mypy.ini"]
        additional_dependencies: [boto3==1.24.64,botocore==1.27.64,discord.py==2.0.1, psycopg2-binary, types-psycopg2, boto3-stubs]
