version: "3.8"
# ONLY USED FOR LOCAL DEVELOPMENT

services:

  # renzen-app:
  #   environment:
  #     - RUN_LOCAL=1
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true
  #     - FAST_REFRESH=false
  #   image: renzen-app
  #   build:
  #     context: renzen-app
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes: ['./renzen-app:/data/app/']

  bot:
    environment:
      - RUN_LOCAL=1
      - DEV_DISCORD_TOKEN=${DEV_DISCORD_TOKEN:?err}
    image: bot-app
    build:
      context: renzen
      dockerfile: src/bot/Dockerfile
    ports:
      - "80:8000"
    # depends_on:
    #   db:
    #     condition: service_healthy
    #   rabbitmq:
    #     condition: service_healthy
    volumes: ['./renzen:/data/app/']
    deploy:
      restart_policy:
        condition: on-failure
        # delay: 5s
        # max_attempts: 3
        # window: 120s

  site:
    environment:
      - RUN_LOCAL=1
      - GITHUB_LOCAL_OAUTH_CLIENT_SECRET=${GITHUB_LOCAL_OAUTH_CLIENT_SECRET}
    image: site-app
    build:
      context: renzen
      dockerfile: src/site/Dockerfile
    ports:
      - "81:80"
    # depends_on:
    #   db:
    #     condition: service_healthy
    #   rabbitmq:
    #     condition: service_healthy
    volumes: ['./renzen:/data/app/']
    deploy:
      restart_policy:
        condition: on-failure
        # delay: 5s
        # max_attempts: 3
        # window: 120s

  db:
    image: postgres
    restart: always
    container_name: postgres
    # network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
#     volumes:
#       - pgdata:/var/lib/postgresql/data

  # http://localhost:15432/
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    # volumes:
    #   - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

# volumes:
#   pgdata:

# adminer:
#   image: adminer
#   restart: always
#   ports:
#     - 8080:8080

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
