version: "3.8"
# ONLY USED FOR LOCAL DEVELOPMENT

services:

  bot:
    environment:
      - RUN_LOCAL=1
    image: bot-app
    build:
      context: renzen
      dockerfile: src/bot/Dockerfile
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  site:
    environment:
      - RUN_LOCAL=1
    image: site-app
    build:
      context: renzen
      dockerfile: src/site/Dockerfile
    ports:
      - "81:80"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:

# adminer:
#   image: adminer
#   restart: always
#   ports:
#     - 8080:8080

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
