version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...

      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - IMAGE_TAG="${CURRENT_ENVIRONMENT}-LatestBot"
      - IMAGE_TAG_SITE="${CURRENT_ENVIRONMENT}-LatestSite"
      - IMAGE_REPO_NAME="${CURRENT_ENVIRONMENT}-bot-repo"

      - echo $AWS_ACCOUNT_ID
      - echo $IMAGE_TAG
      - echo $IMAGE_TAG_SITE
      - echo $IMAGE_REPO_NAME

      - echo $CURRENT_ENVIRONMENT

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - pip3 install pytest

  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`

      - printenv

      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)

      - IMAGE_TAG="${CURRENT_ENVIRONMENT}-LatestBot"
      - IMAGE_TAG_SITE="${CURRENT_ENVIRONMENT}-LatestSite"
      - IMAGE_REPO_NAME="${CURRENT_ENVIRONMENT}-bot-repo"

      - echo $AWS_ACCOUNT_ID
      - echo $IMAGE_TAG
      - echo $IMAGE_TAG_SITE
      - echo $IMAGE_REPO_NAME

      - echo Building the Docker image bot...
      # Builds using Dockerfile named "Dockerfile" in root as context by default
      # Name and optionally a tag in the 'name:tag' format
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f renzen/src/bot/Dockerfile renzen  # `-t tag .`
      # tags built image with registry host name to push to private repository
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - echo Building the Docker image site...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG_SITE -f renzen/src/site/Dockerfile renzen
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG_SITE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG_SITE

  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`

      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)

      - IMAGE_TAG="${CURRENT_ENVIRONMENT}-LatestBot"
      - IMAGE_TAG_SITE="${CURRENT_ENVIRONMENT}-LatestSite"
      - IMAGE_REPO_NAME="${CURRENT_ENVIRONMENT}-bot-repo"

      - echo $AWS_ACCOUNT_ID
      - echo $IMAGE_TAG
      - echo $IMAGE_TAG_SITE
      - echo $IMAGE_REPO_NAME

      - pytest

      - echo Pushing the Docker image bot...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - echo Pushing the Docker image site...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG_SITE

      - echo Writing image definitions file...
      - mkdir bot
      - cd bot
      - printf '[{"name":"%s-bot-container","imageUri":"%s"}]' $CURRENT_ENVIRONMENT $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
      - cd ..
      - mkdir site
      - cd site
      - printf '[{"name":"%s-site-container","imageUri":"%s"}]' $CURRENT_ENVIRONMENT $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG_SITE > imagedefinitions.json
      - cd ..

      - python3 cloudformation/export_parameters.py

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    secondary_artifact_name_1:
      base-directory: bot
      files:
        - imagedefinitions.json
      name: secondary_artifact_name_1
    secondary_artifact_name_2:
      base-directory: site
      files:
        - imagedefinitions.json
      name: secondary_artifact_name_2
    secondary_artifact_name_3:
      files:
        - STACK_PARAMETERS.json
      name: secondary_artifact_name_3
