AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "me-test"
Description: "Stack used to start and stop bot and pipeline."

Resources:

  # if using a custom domain name for loadbalancer

  # HostedZoneResource:
  #   Type: "AWS::Route53::HostedZone"
  #   Properties:
  #     HostedZoneConfig:
  #       Comment: 'My hosted zone for renadvent.io'
  #     Name: 'api.renzen.io'
  #     VPCs:
  #       -
  #         VPCId: !ImportValue myVPC
  #         VPCRegion: 'us-west-1'



      #   -
      #     VPCId: 'vpc-abcd1234'
      #     VPCRegion: 'ap-northeast-1'
      #   -
      #     VPCId: 'vpc-efgh5678'
      #     VPCRegion: 'us-west-2'
      # HostedZoneTags:
      #   -
      #     Key: 'SampleKey1'
      #     Value: 'SampleValue1'
      #   -
      #     Key: 'SampleKey2'
      #     Value: 'SampleValue2'

  myDNSRecord:
    Type: AWS::Route53::RecordSet
    # DependsOn: HostedZoneResource
    Properties:
      #HostedZoneName: 'renzen.io'
      HostedZoneId: Z07096223ERVZ2460AEFE  # FROM CONSOLE
      # HostedZoneId: !Ref 'HostedZoneResource'
      Comment: DNS name for my instance.
      Name: 'a.renzen.io'
      # Name: !Join ['', [!Ref 'Ec2Instance', ., !Ref 'AWS::Region', ., !Ref 'HostedZone', .]]
      Type: A
      # TTL: 60
      AliasTarget:
        DNSName: !ImportValue myLoadBalancerDNSName
        # HostedZoneId: !Ref 'HostedZoneResource'
        HostedZoneId: !ImportValue myLoadBalancerCanonicalHostedZoneID
      # ResourceRecords:
      # - !GetAtt myLoadBalancer.PublicIp
