AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "me-test"
Description: "Sets up Github connection"

Resources:
  BotGithubConnection:
    Type: "AWS::CodeStarConnections::Connection"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ConnectionName: GithubConnection
      ProviderType: GitHub
Outputs:
  BotGithubConnection:
    Value: !Ref BotGithubConnection
    Export:
      Name: BotGithubConnection
