AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "me-test"
Description: "Sets up Github connection, Discord Secret, and s3 bucket. Exports values to be used for bot stack. ECR repo. console.aws.amazon.com/codesuite/settings/connections to finish setting up Github"

Resources:
  BotGithubConnection:
    Type: "AWS::CodeStarConnections::Connection"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ConnectionName: GithubConnection
      ProviderType: GitHub
  BotGithubConnection2:
    Type: "AWS::CodeStarConnections::Connection"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ConnectionName: GithubConnection2
      ProviderType: GitHub
Outputs:
  BotGithubConnection:
    Value: !Ref BotGithubConnection
    Export:
      Name: BotGithubConnection
  BotGithubConnection2:
    Value: !Ref BotGithubConnection2
    Export:
      Name: BotGithubConnection2
