"""Constants."""

import os

CURRENT_ENVIRONMENT = os.getenv("CURRENT_ENVIRONMENT")

NOTIFICATION_USER = 273685734483820554
PRODUCTION_ALERTS_CHANNEL = 1050487198882992268
STAGING_ALERTS_CHANNEL = 1050487229631451238

_GITHUB_LOCAL_OAUTH_CLIENT_ID = "b981ba10feff55da4f93"
_GITHUB_STAGING_OAUTH_CLIENT_ID = "b18f1b8d5f29ed35f45c"
_GITHUB_PRODUCTION_OAUTH_CLIENT_ID = ""

_LOCAL_PREFIX = "http://localhost:81/"
_STAGING_PREFIX = "http://staging.renzen.io/"
_PRODUCTION_PREFIX = "http://production.renzen.io/"

if CURRENT_ENVIRONMENT == "staging":
    CURRENT_PREFIX = _STAGING_PREFIX
    GITHUB_CLIENT_ID = _GITHUB_STAGING_OAUTH_CLIENT_ID
elif CURRENT_ENVIRONMENT == "production":
    CURRENT_PREFIX = _PRODUCTION_PREFIX
    GITHUB_CLIENT_ID = _GITHUB_PRODUCTION_OAUTH_CLIENT_ID
else:
    CURRENT_PREFIX = _LOCAL_PREFIX
    GITHUB_CLIENT_ID = _GITHUB_LOCAL_OAUTH_CLIENT_ID

GITHUB_OAUTH_REDIRECT_URI = f"{CURRENT_PREFIX}api/auth/github"
GITHUB_CALLBACK_URI = CURRENT_PREFIX

GITHUB_OAUTH_PATH = "/"
